### ISSUE TITLE
Error to build

### ISSUE THREAD

**Issue by hallucino** [bfops/playform#160]
To build the server or client I got this error:
github.com-0a35038f75765ae4/clippy-0.0.15/src/consts.rs:324:30: 324:37 error: variable `UnUniq` from pattern #1 is not bound in pattern #2 [E0408]
github.com-0a35038f75765ae4/clippy-0.0.15/src/consts.rs:324                     UnUniq | UnDeref => Some(o),
                                                                                                                            ^~~~~~~
github.com-0a35038f75765ae4/clippy-0.0.15/src/len_zero.rs:111:58: 111:70 error: use of undeclared type name `SpannedIdent` [E0412]
github.com-0a35038f75765ae4/clippy-0.0.15/src/len_zero.rs:111 fn check_len_zero(cx: &LateContext, span: Span, method: &SpannedIdent,
                                                                                                                                                          ^~~~~~~~~~~~
github.com-0a35038f75765ae4/clippy-0.0.15/src/len_zero.rs:111:58: 111:70 help: run `rustc --explain E0412` to see a detailed explanation
github.com-0a35038f75765ae4/clippy-0.0.15/src/shadow.rs:261:38: 261:44 error: unresolved name `UnUniq` [E0425]
github.com-0a35038f75765ae4/clippy-0.0.15/src/shadow.rs:261         ExprUnary(op, ref inner) => (UnUniq == op || UnDeref == op) &&
                                                                                                                                    ^~~~~~
github.com-0a35038f75765ae4/clippy-0.0.15/src/shadow.rs:261:38: 261:44 help: run `rustc --explain E0425` to see a detailed explanation
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:181:5: 183:6 error: method `visit_opt_lifetime_ref` is not a member of trait `Visitor` [E0407]
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:181     fn visit_opt_lifetime_ref(&mut self, _: Span, lifetime: &'v Option<Lifetime>) {
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:182         self.record(lifetime);
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:183     }
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:181:5: 183:6 help: run `rustc --explain E0407` to see a detailed explanation
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:186:5: 188:6 error: method `visit_lifetime_ref` is not a member of trait `Visitor` [E0407]
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:186     fn visit_lifetime_ref(&mut self, lifetime: &'v Lifetime) {
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:187         self.record(&Some(*lifetime));
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:188     }
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:186:5: 188:6 help: run `rustc --explain E0407` to see a detailed explanation
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:191:5: 191:60 error: method `visit_lifetime_bound` is not a member of trait `Visitor` [E0407]
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:191     fn visit_lifetime_bound(&mut self, _: &'v Lifetime) { }
                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
github.com-0a35038f75765ae4/clippy-0.0.15/src/lifetimes.rs:191:5: 191:60 help: run `rustc --explain E0407` to see a detailed explanation
error: aborting due to 6 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `clippy`.

version:
rustc 1.5.0-nightly (f5a015892 2015-10-01)

**Comment by bfops** [comment]
rust-clippy was failing to build for a while, so the cargo lockfile is tied to older packages for an older rustc. Maybe a `cargo update` will fix it? If not, I'll take a look when I get home.

**Comment by hallucino** [comment]
Seem to work with clippy 0.0.18.

**Comment by hallucino** [comment]
I got this error now, after a cargo update/build:
playform/voxel/./src/impls/surface_vertex.rs:103:7: 103:25 error: binary operation `+` cannot be applied to type `cgmath::vector::Vector3<f32>` [E0369]
playform/voxel/./src/impls/surface_vertex.rs:103       weighted!(0, 0, 0) +
                                                                                ^~~~~~~~~~~~~~~~~~
playform/voxel/./src/impls/surface_vertex.rs:103:7: 103:25 note: in this expansion of weighted! (defined in playform/voxel/./src/impls/surface_vertex.rs)
playform/voxel/./src/impls/surface_vertex.rs:103:7: 103:25 help: run `rustc --explain E0369` to see a detailed explanation
playform/voxel/./src/impls/surface_vertex.rs:112:36: 112:62 error: the type of this value must be known in this context
playform/voxel/./src/impls/surface_vertex.rs:112     let vertex = Point3::from_vec(&vertex.div_s(total_weight));
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `voxel`.

**Comment by hallucino** [comment]
And for the client:
src/camera.rs:50:5: 50:13 error: binary operation `*` cannot be applied to type `cgmath::matrix::Matrix4<f32>` [E0369]
src/camera.rs:50     self.fov * self.rotation * self.translation
                     ^~~~~~~~
src/camera.rs:50:5: 50:13 help: run `rustc --explain E0369` to see a detailed explanation
src/camera.rs:69:21: 69:34 error: binary operation `*` cannot be applied to type `cgmath::matrix::Matrix4<f32>` [E0369]
src/camera.rs:69     self.rotation = self.rotation * mat;
                                     ^~~~~~~~~~~~~
src/camera.rs:69:21: 69:34 help: run `rustc --explain E0369` to see a detailed explanation
error: aborting due to 2 previous errors
Could not compile `playform-client`.

**Comment by bfops** [comment]
Interesting, I'd swear that code just looks broken, except it works for me for some lockfile and some rustc. Looks like things important things have changed. If you can't get it working easily, I'll take a look later. (If you can get it working, submit a PR please!)

Also FYI, it's likely to not run very well, if at all. I have no code that tries to infer a good render distance or LOD, so those take manual tweaking. I think it also requires OpenGL 3.3+.

**Comment by bfops** [comment]
Taking a look now. Turns out `clippy-0.0.18` builds on nightly 2015-10-01, but not on 2015-10-02!

**Comment by bfops** [comment]
Fixed! Thanks for the help!

I'll also add something to the README about tweaking various performance parameters, because I'm bad at using config files.
